version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /app
      - type: volume
        source: user
        target: /root
volumes:
  user:
